
#FROM i386/ubuntu
FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y build-essential
RUN apt-get install -y cmake
RUN apt-get install -y ninja-build
RUN apt-get install -y libicu-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libglib2.0
RUN apt-get install -y pkg-config
RUN apt-get install -y gtk-doc-tools
RUN apt-get install -y cppcheck

RUN apt-get install -y gcc-9-multilib
RUN apt-get install -y gobject-introspection libgirepository1.0-dev

RUN apt-get install -y g++ rsync zip openssh-server make
RUN mkdir -p /var/run/sshd

RUN apt-get install -y gdb

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && ssh-keygen -A

RUN useradd -m -d /home/user -s /bin/bash -G sudo user
USER user
CMD service ssh start && bash

WORKDIR /home/user

RUN git clone https://github.com/libical/libical
RUN mkdir ~/libical/build
WORKDIR /home/user/libical

RUN git checkout HEAD~4

WORKDIR /home/user/libical/build

RUN cmake -DICAL_GLIB=true -DGOBJECT_INTROSPECTION=true -DLIBICAL_DEVMODE_MEMORY_CONSISTENCY=true ..
RUN cmake --build .



# run this image like
# docker run -p 5000:22 -i -t libical

# don't forget to specify a password for user 'user' like so
# passwd user
